import test from 'node:test';
import assert from 'node:assert/strict';
import {e,link,paperInput,filteredPapers,counts,needsAttention,timeLabel} from '../web/core.js';
const p = {id:'1',title:'Layer Generation',authors:['Alice'],topics:['图层'],notes:'alpha control',abstract:'',doi:'',arxiv_id:'',status:'inbox',is_demo:false,year:2025,updated_at:'2026-01-01',resources:[]};
const demo = {...p,id:'2',title:'Layout',notes:'',is_demo:true,status:'baseline',year:2026,topics:['Layout'],updated_at:'2026-02-01',resources:[{latest:null}]};
test('escapes all HTML special characters',()=>assert.equal(e('<img x="1" onerror=\'x\'>&'), '&lt;img x=&quot;1&quot; onerror=&#39;x&#39;&gt;&amp;'));
test('rejects executable links',()=>assert.equal(link('javascript:alert(1)'),'#'));
test('rejects embedded credentials',()=>assert.equal(link('https://user:secret@example.org'),'#'));
test('allows normal HTTPS URLs',()=>assert.equal(link('https://example.org'),'https://example.org/'));
test('matches notes case insensitively',()=>assert.equal(filteredPapers([p,demo],{query:'ALPHA'}).length,1));
test('filters topics',()=>assert.equal(filteredPapers([p,demo],{topic:'图层'})[0].id,'1'));
test('filters reading status',()=>assert.equal(filteredPapers([p,demo],{status:'baseline'})[0].id,'2'));
test('can exclude all demo papers',()=>assert.equal(filteredPapers([p,demo],{hideDemo:true}).length,1));
test('sorts by year',()=>assert.equal(filteredPapers([p,demo],{sort:'year'})[0].year,2026));
test('does not mutate the input list',()=>{const arr=[p,demo];filteredPapers(arr);assert.equal(arr[0].id,'1');});
test('missing resource does not become a negative finding',()=>assert.equal(filteredPapers([p],{attention:true}).length,0));
test('uninspected resources require attention',()=>assert.ok(needsAttention({latest:null})));
test('gated resources are not treated as failed checks',()=>assert.equal(needsAttention({latest:{status:'gated'}}),false));
test('indeterminate observations need attention',()=>assert.ok(needsAttention({latest:{status:'indeterminate'}})));
test('counts are calculated from stored records',()=>assert.deepEqual(counts([p,demo]),{papers:2,resources:1,checked:0,pending:1,baseline:1,topics:2}));
test('paper payload excludes resource and demo flags',()=>{const input=paperInput(demo);assert.equal(input.resources,undefined);assert.equal(input.is_demo,undefined);assert.equal(input.title,'Layout');});
test('invalid timestamps do not crash render',()=>assert.equal(timeLabel('invalid'),'时间未知'));
