/** The workbench's pure logic, against the fixture that `result_model.normalize` really wrote.
 *
 * `tests/fixtures/search-result.json` is generated by `.data/gen_search_fixture.py` through the same
 * code path as `re0 paper search --json`, and a Python test regenerates and compares it — so these
 * assertions are about the real shape, not about a hand-written guess at it. The papers in it are
 * fictional and say so in their own `note`.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {
  AUDIT_COMPONENTS, AUDIT_LABELS, COMPONENT_LABELS, MATRIX_COLUMNS, approvalItems, bibtex,
  candidates, commandFor, csvCell, facets, filterSort, labelled, matrix, matrixCsv, parseResult,
  safeLink, summary,
} from '../web/search-core.js';

const raw = readFileSync(new URL('./fixtures/search-result.json', import.meta.url), 'utf8');
const result = JSON.parse(raw);

test('accepts the versioned result the CLI writes', () => {
  const parsed = parseResult(raw);
  assert.equal(parsed.ok, true);
  assert.equal(parsed.warning, undefined);
  assert.equal(parsed.result.schema_version, '1');
});

test('refuses something that is not JSON, and says so', () => {
  assert.equal(parseResult('not json').ok, false);
  assert.match(parseResult('not json').error, /不是合法 JSON/);
});

test('refuses a payload with no schema_version rather than rendering an empty page', () => {
  const parsed = parseResult('{"documents":[]}');
  assert.equal(parsed.ok, false);
  assert.match(parsed.error, /schema_version/);
});

test('names the matrix file when one is loaded by mistake', () => {
  // Both files carry schema_version 1; rendering the matrix as a result would show zero candidates,
  // which reads as "the search found nothing".
  const parsed = parseResult('{"schema_version":"1","rows":[],"approval":[]}');
  assert.equal(parsed.ok, false);
  assert.match(parsed.error, /--resource-matrix/);
});

test('renders a newer schema with a warning instead of refusing it', () => {
  const parsed = parseResult('{"schema_version":"2","documents":[]}');
  assert.equal(parsed.ok, true);
  assert.match(parsed.warning, /schema_version 2/);
});

test('the summary carries the window that was actually requested', () => {
  const info = summary(result);
  assert.deepEqual(info.queries, ['layer decomposition', 'layered generation']);
  assert.equal(info.requested.start_year, 2023);
  assert.equal(info.requested.limit, 10);
  assert.equal(info.state, 'partial');
  assert.equal(info.attempts.length, 3);
  assert.equal(info.documents, 4);
  assert.equal(info.duplicates_merged, 2);
  assert.equal(info.dropped_out_of_range, 5);
  assert.equal(info.incomplete, true);
});

test('a failed source is a failure, not a zero', () => {
  const info = summary(result);
  const failed = info.sources.find(item => item.name === 'semanticscholar');
  assert.equal(failed.failed, true);
  assert.match(failed.error, /429/);
  assert.equal(info.sources.find(item => item.name === 'crossref').count, 2);
});

test('the audit coverage keeps its denominators', () => {
  const audit = summary(result).audit;
  assert.equal(audit.papers, 4);
  assert.equal(audit.name_search.denominator, 4);
  assert.equal(audit.name_search.budget, 6);
  assert.equal(audit.name_search.states.failed, 1);
  assert.equal(audit.candidates.found, 2);
});

test('the fixture says it is fictional, and the page shows that', () => {
  assert.match(summary(result).note, /虚构/);
});

test('a field this version does not describe is reported, not dropped', () => {
  const rows = candidates(result);
  assert.deepEqual(rows[1].unrecognised, {future_provider_field: 'carried, not understood'});
});

test('candidates read the publication label out of the payload', () => {
  const rows = candidates(result);
  assert.equal(rows[0].publication, 'venue');
  assert.equal(rows[0].publication_label, result.documents[0].publication.label);
  assert.equal(rows[1].publication, 'preprint');
  // No local table to drift: a missing label falls back to the raw token, not to an invented one.
  assert.equal(rows[0].publication_label.length > 0, true);
});

test('identifier links come first, and a record page that is one of them is not repeated', () => {
  // Every paper in the fixture has its record URL equal to its DOI or arXiv link, so the third entry
  // is dropped rather than listed twice.
  assert.deepEqual(candidates(result)[0].links.map(item => item.label), ['arXiv', 'DOI']);
  const distinct = {arxiv_id: '', doi: '', paper_url: 'https://example.org/record'};
  const rows = candidates({documents: [{paper: distinct}]});
  assert.deepEqual(rows[0].links.map(item => item.label), ['record']);
});

test('filters narrow the view without touching the result', () => {
  const rows = candidates(result);
  assert.equal(rows.length, 4);
  assert.equal(filterSort(rows, {query: 'LayerKit'}).length, 1);
  assert.equal(filterSort(rows, {year: '2025'}).length, 1);
  assert.equal(filterSort(rows, {source: 'arxiv'}).length, 2);
  assert.equal(filterSort(rows, {publication: 'preprint'}).length, 1);
  assert.equal(filterSort(rows, {openOnly: true}).length, 1);
  assert.equal(filterSort(rows, {}).length, 4);
  assert.equal(rows.length, 4, 'the loaded result is not mutated by a filter');
});

test('sorting by citations puts an unknown count last', () => {
  const rows = filterSort(candidates(result), {sort: 'citations'});
  assert.deepEqual(rows.map(row => row.citations), [302, 128, 41, null]);
});

test('which services reported a work is a field, not a sentence to parse', () => {
  assert.deepEqual(candidates(result)[0].sources, ['crossref', 'openalex']);
});

test('facets only offer choices that occur', () => {
  const info = facets(candidates(result));
  assert.deepEqual(info.years, [2026, 2025, 2024, 2023]);
  assert.ok(info.publications.every(item => item.value && item.label));
  assert.ok(info.sources.includes('crossref'));
});

test('every audited candidate becomes a matrix row', () => {
  const found = matrix(result);
  assert.equal(found.rows.length, 4);
  assert.equal(found.papers, 4);
  assert.equal(found.comparable, true);
  assert.equal(found.rows[0].status, 'metadata_readable');
  assert.equal(found.rows[0].coverage.code_training, COMPONENT_LABELS.present);
  assert.equal(found.rows[0].licences.code, 'MIT');
  assert.ok(found.rows[0].sources.length, 'an affirmative row keeps the link it rests on');
});

test('a paper with no candidate still gets a row that says which kind of absence it is', () => {
  const rows = matrix(result).rows;
  const nothing = rows.find(row => row.paper_title.startsWith('A Survey'));
  assert.equal(nothing.status, 'not_found_in_scope');
  assert.match(nothing.blockers[0], /检查范围内未找到/);
  const failed = rows.find(row => row.paper_title.startsWith('Depth-Aware'));
  assert.equal(failed.status, 'access_failed');
  assert.match(failed.blockers[0], /检索未完成/);
  assert.ok(failed.limitations.some(item => item.includes('403')), 'the reason travels with the row');
});

test('a clean official row has no blockers, an unconfirmed one has several', () => {
  const rows = matrix(result).rows;
  assert.deepEqual(rows[0].blockers, []);
  const gated = rows[1];
  assert.ok(gated.blockers.length >= 4);
  assert.ok(gated.blockers.some(text => text.includes('adapter')));
  assert.ok(gated.blockers.some(text => text.includes('归属')));
});

test('every matrix row keeps the labels for all eight artifact classes', () => {
  matrix(result).rows.forEach(row => {
    assert.deepEqual(Object.keys(row.coverage), AUDIT_COMPONENTS);
  });
});

test('a javascript: URL in a hand-edited file becomes nothing, not a link', () => {
  const hostile = JSON.parse(JSON.stringify(result));
  hostile.documents[0].resource_audits[0].resource_url = 'javascript:alert(1)';
  hostile.documents[0].resource_audits[0].evidence[0].source_url = 'javascript:alert(2)';
  const row = matrix(hostile).rows[0];
  assert.equal(row.resource_url, '');
  assert.ok(!row.sources.some(url => url.startsWith('javascript:')), 'the listing link is dropped');
  assert.ok(row.sources.length, 'the component links that are real http(s) are kept');
  assert.equal(safeLink('https://user:pass@example.org'), '');
});

test('BibTeX escapes what LaTeX would otherwise execute', () => {
  const text = bibtex([{title: 'A 100% {real} & <fake> paper', authors: ['Ada L.', 'Grace H.'],
                        year: 2025, doi: '10.99999/x', arxiv_id: '', links: [], publication: 'venue'}]);
  assert.ok(text.startsWith('@misc{re0_'));
  assert.ok(text.includes('100\\%'));
  assert.ok(text.includes('\\{real\\}'));
  assert.ok(text.includes('\\&'));
  assert.ok(text.includes('Ada L. and Grace H.'));
  assert.ok(text.includes('<fake>'), 'angle brackets are not LaTeX specials and stay literal');
});

test('a preprint-only candidate says so in the citation', () => {
  const rows = candidates(result);
  const text = bibtex(rows.slice(1, 2));
  assert.match(text, /preprint only in the sources this search reached/);
  assert.doesNotMatch(bibtex(rows.slice(0, 1)), /preprint only/);
});

test('CSV neutralises a cell a spreadsheet would execute', () => {
  assert.equal(csvCell('=SUM(A1)'), "'=SUM(A1)");
  assert.equal(csvCell('-2'), "'-2");
  assert.equal(csvCell('@cmd'), "'@cmd");
  assert.equal(csvCell('a\nb'), 'a b');
});

test('the CSV export has one header and one line per row', () => {
  const csv = matrixCsv(matrix(result).rows);
  const lines = csv.trimEnd().split('\r\n');
  assert.equal(lines.length, 5);
  assert.deepEqual(lines[0].split(','), MATRIX_COLUMNS);
  assert.ok(MATRIX_COLUMNS.includes('record_kind'));
});

test('the approval payload carries only papers a source supports', () => {
  const items = approvalItems(result);
  assert.equal(items.length, 2);
  assert.ok(items.every(item => item.paper.title && item.audits.length));
  assert.equal(items[0].paper.title, result.documents[0].paper.title);
});

test('the reproduced command uses what the file records, and lists what it does not', () => {
  const command = commandFor(result);
  assert.match(command.command, /--queries "layer decomposition\|layered generation"/);
  assert.match(command.command, /--start-year 2023/);
  assert.match(command.command, /--max-papers 10/);
  assert.match(command.command, /--find-artifacts 6/);
  assert.deepEqual(command.unknowns, []);
});

test('an older file gets placeholders instead of invented flags', () => {
  const older = JSON.parse(JSON.stringify(result));
  delete older.coverage.requested;
  const command = commandFor(older);
  assert.match(command.command, /--start-year <结果未记录>/);
  assert.ok(command.unknowns.some(text => text.includes('年份窗口')));
});

test('a label falls back to the raw token rather than to a guess', () => {
  assert.equal(labelled(AUDIT_LABELS, 'metadata_readable'), '元数据可读（metadata_readable）');
  assert.equal(labelled(AUDIT_LABELS, 'some_new_state'), 'some_new_state');
  assert.equal(labelled(AUDIT_LABELS, ''), '');
});
